---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3-dataplane-interrupt

resources:
- ns-vl3-dataplane-interrupt.yaml
- netsvc.yaml
- client.yaml
- ../../../apps/nse-vl3-vpp
- ../../../apps/vl3-ipam


patchesStrategicMerge:
- nse-patch.yaml
