---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: forwarder-vpp
spec:
  selector:
    matchLabels:
       app: forwarder-vpp
  template:
    spec:
      containers:
        - name: forwarder-vpp
          env:
            - name: NSM_VPP_INIT
              value: AF_XDP
