---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      pr-number: ${{ steps.find-pull-request.outputs.number }}
    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1.5.0
        id: find-pull-request
        with:
          branch: ${{ github.event.workflow_run.head_branch }}

      - run: echo "Pull Request ${number} (${sha})"
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}

      - name: Merge PR
        uses: ridedott/merge-me-action@master
        if: steps.find-pull-request.outputs.number
        with:
          GITHUB_LOGIN: github-actions
          ENABLED_FOR_MANUAL_CHANGES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAXIMUM_RETRIES: 25

  delete-release-branch:
    name: Delete Release Branch
    runs-on: ubuntu-latest
    needs: automerge
    if: ${{ needs.automerge.outputs.pr-number && contains(github.event.workflow_run.head_branch, 'release/') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Delete release branch
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git push origin --delete ${{ github.event.workflow_run.head_branch }}
