---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Find merged PR
        uses: jwalton/gh-find-current-pr@v1.0.2
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR
        run: |
          [[ -z $(echo ${{ steps.findPr.outputs.number }}) ]] && exit 1 || exit 0

      - name: Merge PR
        uses: ridedott/merge-me-action@master
        if: success() && steps.findPr.outputs.number
        with:
          GITHUB_LOGIN: github-actions
          ENABLED_FOR_MANUAL_CHANGES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAXIMUM_RETRIES: 25

  delete-release-branch:
    name: Delete Release Branch
    runs-on: ubuntu-latest
    needs: automerge
    if: ${{ contains(github.event.workflow_run.head_branch, 'release/') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Delete release branch
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git push origin --delete ${{ github.event.workflow_run.head_branch }}
