---
name: Check failed auto-pull-request workflows
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - "main"
jobs:
  check-failed-workflows:
    strategy:
      matrix:
        repository:
          - cmd-nsmgr
          - cmd-nsmgr-proxy
          - cmd-registry-memory
          - cmd-registry-proxy-dns
          - cmd-nse-vfio
          - cmd-nse-remote-vlan
          - cmd-nsc-init
          - cmd-ipam-vl3
          - cmd-map-ip-k8s
          - cmd-admission-webhook-k8s
          - cmd-cluster-info-k8s
    name: Check failed auto-pull-request workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check Failed Workflows
        run: |
          repo="deployments-k8s"
          owner="NikitaSkrynnik"

          runs=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$owner/$repo/actions/runs?branch=update/$owner/${{ matrix.repository }})
          
          lastRun=$(echo $runs | jq '[.workflow_runs | .[] | select(.name=="Pull Request on update/* Branch Push")][0]')
          lastRunConclusion=$(echo $lastRun | jq -r '.conclusion')

          echo Conclusion for ${{ matrix.repository }} is $lastRunConclusion
          if [ "$lastRunConclusion" != "success" ]; then
            runID=$(echo $lastRun | jq -r '.id')
            gh run rerun $runID --repo $owner/$repo
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}