---
name: Pull Request for pending update/* branches
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  auto-pull-request:
    name: Pull Request on update/* Branch Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create a Pull Request
        run: |
          branches=$(git branch -r --list "update/*")
          echo $branches
        env:
          GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}