---
name: ci
on:
  pull_request:
  push:
    branches:
      - "release/*"
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: .yamllint.yml
          strict: true

  image-check:
    name: Check that image is pullable
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Check images
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_on: timeout
          command: |
            repoName=${GITHUB_REF#refs/heads/update/networkservicemesh/}
            images=$(grep -roh 'apps' -e "ghcr.io/networkservicemesh/ci/${repoName}.*")
            for image in $images; do
              docker pull $image
            done
