---
name: Pull Request on update/* Branch Push
on:
  push:
    branches:
      - update/**
jobs:
  auto-pull-request:
    name: Pull Request on update/* Branch Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a Pull Request
        run: |
          pullRequestBody =$(git log --pretty='format:%B' -1 | sed '/^$/d;$d' | sed 's/#/# /g')

          local timeout_sec=300
          local t0=$(date '+%s')
          local remaining=$(expr ${timeout_sec} + ${t0} - "$(date '+%s')")
          while [[ ${remaining} -gt 0 ]]
          do
              gh pr create -B 'main' -H ${{ github.ref }} --title 'New pr' --body $pullRequestBody
              if [ $? -eq 0 ]; then
                return 0
              fi
              remaining=$(expr ${timeout_sec} + ${t0} - "$(date '+%s')")
          done
        env:
          GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
