---
name: Release
on:
  push:
    branches:
      - "release/*"
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  get-tag:
    name: Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-step.outputs.tag }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Tag env
        run: |
          branch=${{ github.event.ref }}
          echo '::set-output name=tag::'${branch#refs/heads/release/}
        id: tag-step

  create-release:
    name: Create release
    needs: [get-tag]
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@fix-release
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
