---
name: Update references
on:
  push:
    branches:
      - main
jobs:
  update-refs:
    name: Update references
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push' }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update references
        shell: bash {0} # Makes script continue execution even if some commands return non-zero exit code
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "nsmbot"
          git checkout test
          git reset --hard main
          rm -f ./to-reft.sh
          git add -- .
          git commit -s -m "remove to ref"
          git push origin test

          echo "Exit code: $?"
